# Generated by Django 3.1.4 on 2023-11-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_category',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course_category',
            name='desc',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_category',
            name='image',
            field=models.ImageField(default='', upload_to='static/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_category',
            name='resource',
            field=models.FileField(default='', upload_to='files/resource'),
            preserve_default=False,
        ),
    ]
