# Generated by Django 3.1.4 on 2023-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepoint', '0003_course_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_information',
            name='course_content',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
