# Generated by Django 3.1.4 on 2023-11-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codepoint', '0004_course_information_course_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_information',
            name='course_content',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
